// flow-typed signature: c57cdf58c8c1e8184b1ba517fbd13518
// flow-typed version: <<STUB>>/node-uuid_v1.4.7

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-uuid'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-uuid' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-uuid/benchmark/benchmark' {
  declare module.exports: any;
}

declare module 'node-uuid/test/compare_v1' {
  declare module.exports: any;
}

declare module 'node-uuid/test/test' {
  declare module.exports: any;
}

declare module 'node-uuid/uuid' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-uuid/benchmark/benchmark.js' {
  declare module.exports: $Exports<'node-uuid/benchmark/benchmark'>;
}
declare module 'node-uuid/test/compare_v1.js' {
  declare module.exports: $Exports<'node-uuid/test/compare_v1'>;
}
declare module 'node-uuid/test/test.js' {
  declare module.exports: $Exports<'node-uuid/test/test'>;
}
declare module 'node-uuid/uuid.js' {
  declare module.exports: $Exports<'node-uuid/uuid'>;
}
